---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Harness_portal
  title: HarnessCore
  description: Harness portal code
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: Team-A
  domain: core
  type: service
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Access-control
  title: AccessControl
  description: About Access Control
  annotations:
    backstage.io/techdocs-ref: dir:./access-control
spec:
  type: service
  lifecycle: production
  subcomponentOf: Harness_portal
  owner: Team-A
  domain: core