apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: HarnessCore
  description: Harness portal code
  annotations:
    backstage.io/techdocs-ref: dir:.
  name: Harness_portal
spec:
  owner: Team-A
  type: service
  lifecycle: production
