site_name: Harness-Core

nav:
  - Intro: 'index.md'
  - Services:
    - access-control : '!include ./access-control/mkdocs.yml'
    - product : '!include ./product/mkdocs.yml'
plugins:
  - monorepo
  - techdocs-core
