#Any edit in this file should accompany an increment in version.
name : settingsConfiguration
version : 1
settings :
  - identifier: test_setting_CI
    name: Test CI setting
    category : CI
    groupIdentifier: group_1
    defaultValue: default
    valueType : STRING
    allowOverrides : false
    allowedScopes :
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: test_setting_CI_2
    name: Test CI setting
    category: CI
    defaultValue: 2
    valueType: NUMBER
    groupIdentifier: group_1
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
  - identifier: test_setting_CI_3
    name: Test CI setting
    category: CI
    groupIdentifier: group_1
    defaultValue: default
    valueType: STRING
    allowedValues: ~
    allowedScopes:
      - ACCOUNT
  - identifier: test_setting_CI_4
    name: Test CI setting
    category: CI
    groupIdentifier: group_2
    defaultValue: default
    valueType: STRING
    allowedValues: ~
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: test_setting_CI_5
    name: Test CI setting
    category: CI
    groupIdentifier: group_2
    defaultValue: default
    valueType: STRING
    allowedValues: ~
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: test_setting_CI_6
    name: Test CI setting
    category: CI
    defaultValue: default
    valueType: STRING
    allowedValues: ~
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: test_setting_CI_7
    name: Test CI setting
    category: CI
    defaultValue: default
    valueType: STRING
    allowedValues: ~
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: test_setting_CD_1
    name: Test CD setting 1
    category : CD
    defaultValue: 8
    valueType : NUMBER
    allowedValues : ~
    allowOverrides: true
    allowedScopes :
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: test_setting_CD_2
    name: Test CD setting 2
    category : CD
    defaultValue: true
    valueType : BOOLEAN
    allowedValues : ~
    allowedScopes :
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: test_setting_CD_3
    name: Test CD setting 3
    category : CD
    defaultValue: ~
    valueType : STRING
    allowedValues : ~
    allowOverrides : true
    allowedScopes :
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: test_setting_CORE_1
    name: Test CORE setting 1
    category : CORE
    defaultValue: false
    valueType : BOOLEAN
    allowedValues :
      - true
      - false
    allowOverrides : true
    allowedScopes :
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: test_setting_CORE_2
    name: Test CORE setting 2
    category : CORE
    defaultValue: ~
    valueType : STRING
    allowedValues : ~
    allowOverrides : true
    allowedScopes :
      - ACCOUNT
  - identifier: test_setting_CORE_3
    name: Test CORE setting 3
    category: CORE
    defaultValue: ~
    valueType: STRING
    allowedValues: ~
    allowOverrides: false
    allowedScopes:
      - ORGANIZATION
      - PROJECT